name: BackPackLimit
version: '${project.version}'
main: com.filizes.backpacklimit.Main
api-version: '1.13'
load: STARTUP
authors: [FILIZES]
softdepend: [PlaceholderAPI]
permissions:
  backpacklimit.bypass:
    default: false